### PR TITLE
Change background image in page-transition

### PR DESCRIPTION
**Pull request by JonathanReisCom**
There is a problem loading the "../img/bg7.jpg" image using the ".scss" file.
So it's solved by loading using the ".js" file.

### CODE REVIEW

**Comment by JonathanReisCom** [comment]
@EINazare can you check, approve and merge this? Ty.

**Comment by EINazare** [comment]
Hello there, @JonathanReisCom ,

Thank you for this PR.
I've checked our product, and it seems that the image loader works as expected.
Can you please share with me a video or a screenshot of the issue?
Also, could you please point the PR to the dev-master branch?
Screen Shot 2020-04-01 at 10 31 57 PM (2)

Thank you,
Manu

**Comment by JonathanReisCom** [comment]
There is really no problem with your current version, the problem only appears when you update the versions.

$ yarn upgrade --latest
$ yarn run dev

Screen Shot 2020-04-01 at 17 50 27
Screen Shot 2020-04-01 at 17 50 57
With these changes it will work again.

**Comment by EINazare** [comment]
Hello again, @JonathanReisCom ,

I'll close this PR for the moment since the changes reflected inside your PR would affect the current code, i.e. the code is functional as is - we are sorry about this.

Best,
Manu

**Pull request closed without merging**
